#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}
hc emit_hook reload
herbstclient set tree_style '╾│ ├└╼─┐'
hc set swap_monitors_to_get_tag 0

# xrandr
xrandr --dpi 96 --output DVI-I-1 --primary --output DVI-D-0 --left-of DVI-I-1 --output HDMI-0 --right-of DVI-I-1 &

# Configure monitors
herbstclient detect_monitors
herbstclient set_monitors 1920x1080+1920+0 1920x1080+0 1920x1080+3840+0
herbstclient rename_monitor 1 left
herbstclient rename_monitor 0 middle
herbstclient rename_monitor 2 right

#--------------------------------------------------#
# Theming
#--------------------------------------------------#
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#0C1F25'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#0D4350'
hc set frame_bg_active_color '#657B83'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 3
hc set frame_gap 2

hc attr theme.active.color '#456A73'
hc attr theme.normal.color '#0D4350'
hc attr theme.urgent.color '#B58900'
hc attr theme.inner_width 1
hc attr theme.inner_color '#0C1F25'
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#0C1F25'
hc attr theme.active.outer_color '#0C1F25'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

#--------------------------------------------------#
# Keybindings
#--------------------------------------------------#

# remove all existing keybindings
hc keyunbind --all
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
Super=Mod4   # Use the super key as the main modifier

# Reload Herbstluftwm
hc keybind $Mod-Shift-r reload

# Exit Herbstluftwm
hc keybind $Mod-Control-BackSpace quit

# Kill client/frame
#hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-Shift-q close_or_remove

# Focus client
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# Move client
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# Create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

# Explode current frame into subframes
hc keybind $Mod-Control-space split explode

# Resizing frames
resizestep=0.03
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-r remove

# Toggle floating client
hc keybind $Mod-s spawn ~/.config/herbstluftwm/Scripts/toggle_single_float.sh

# Toggle fullscreen client
hc keybind $Mod-f fullscreen toggle

# Toggle window decoration on current focused client
hc keybind $Mod-t spawn sh ~/.config/herbstluftwm/Scripts/toggle_window_decoration.sh

hc keybind $Mod-space cycle_monitor -1
hc keybind $Mod-Shift-space cycle_monitor +1

# Tab between the two latest workspaces on the same monitor
hc keybind $Mod-Tab use_previous

# Jump to urgent client
hc keybind $Mod-Shift-a jumpto urgent

# Toggle floating media player
hc keybind $Mod-Shift-m spawn sh ~/.config/herbstluftwm/Scripts/toggle_floating_media.sh

# Toggle virtual dual monitors
#hc keybind $Mod-Shift-n spawn sh ~/.config/herbstluftwm/Scripts/toggle_dual_virtual_monitors.sh

#--------------------------------------------------#
# Applications
#--------------------------------------------------#

# Terminal
hc keybind $Mod-Return spawn urxvt

# Launcher
hc keybind $Mod-p spawn rofi -m -4 -show run -p "oeoeo" -font "xos4Terminus 12"
hc keybind $Mod-Shift-w spawn rofi -m 0 -bw 3 -show window -display-run "Window" -font "xos4Terminus 12"
hc keybind $Mod-Shift-p spawn ~/Scripts/rofi-scripts.sh

# Volume
hc keybind $Mod-plus spawn sh ~/Scripts/volume.sh up
hc keybind $Mod-minus spawn sh ~/Scripts/volume.sh down
hc keybind $Mod-Ctrl-m spawn sh ~/Scripts/volume.sh mute

# Suspend the computer
hc keybind $Mod-Ctrl-Esc spawn sh ~/Scripts/bin/suspend.sh

# Take a screenshot
hc keybind Print spawn sh ~/Scripts/scrot.sh

#--------------------------------------------------#
# Rules
#--------------------------------------------------#

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Gimp
hc rule class=Gimp tag=7 index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

# Firefox
hc rule class="Firefox" tag=8

# Minecraft
hc rule class="Minecraft 1.12.2" tag=4  fullscreen=on

# Unlock, just to be sure
hc unlock

#--------------------------------------------------#
# Tags
#--------------------------------------------------#

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Lock tag to a monitor
lock_tag_to_monitor 1 0
lock_tag_to_monitor 2 1
lock_tag_to_monitor 3 2
lock_tag_to_monitor 4 0
#lock_tag_to_monitor 5 0
lock_tag_to_monitor 6 0
#lock_tag_to_monitor 7 0
#lock_tag_to_monitor 8 0
lock_tag_to_monitor 9 2

# Lock tag to a monitor via keybinding
herbstclient keybind $Mod-t chain \
    , new_attr string tags.focus.my_monitor \
    , substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
    , try and \
        . compare monitors.focus.name != "" \
        . substitute M monitors.focus.name \
                set_attr tags.focus.my_monitor M

# Tags on specic monitors
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        # first check if the tag is locked to some monitor.
        # if so, first focus the monitor
        hc keybind "$Mod-$key" \
            chain , silent substitute M tags."$i".my_monitor \
                        focus_monitor M \
                  , use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Statically define which tag should be send to which monitor
lock_tag_to_monitor() {
    herbstclient chain \
        , new_attr string tags.by-name."$1".my_monitor \
        , set_attr tags.by-name."$1".my_monitor "$2"
}

#--------------------------------------------------#
# Panels
#--------------------------------------------------#

pkill dzen2
~/.config/herbstluftwm/panels/left.sh &
~/.config/herbstluftwm/panels/middle.sh &
~/.config/herbstluftwm/panels/right.sh &

#--------------------------------------------------#
# Mouse settings
#--------------------------------------------------#
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
